cache:
  directories:
    - $HOME/.composer/cache

language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - composer global require --no-interaction --prefer-dist --update-no-dev hirak/prestissimo
  - composer install --no-interaction --prefer-dist

stages:
  - code-analysis
  - test

jobs:
  include:
    - stage: code-analysis
      name: Code Style Check
      php: 7.2
      script: make style-check
    - stage: code-analysis
      name: Static Code Analysis
      php: 7.2
      script: make static-analysis
    - stage: test
      script: make test
